Using while-loop to increasing regularlizer(stability) of the gram matrix until all eigenvalues is postive-definite under numerical method

## Numpy version

In [1]:
import numpy as np

def pos_gram(gram, regularlizer = None):
    _size = len(gram)
    if regularlizer is None:
        # the fraction of float32 is 2**(-23)~10**(-7) we start with 10**(-7) times of maximun element
        regularlizer = np.abs(gram).max()*0.0000001
        if np.abs(gram).max() == 0:
            raise ValueError("gram error, expect matrix with none-zero element")
    
    if regularlizer <= 0:
        raise ValueError("regularlizer error, expect positive, got %s" %(regularlizer))
    
    while True:
        lambdas = np.linalg.eigvalsh(gram + np.identity(_size, np.float32)*regularlizer)
        if lambdas.min() > 0:
            break
        
        regularlizer *= 2.
    
    return gram + np.identity(_size, np.float32)*regularlizer

In [2]:
X = np.identity(2, np.float32)
print(pos_gram(X))

X = np.ones((2,2), np.float32)
print(pos_gram(X))
print(pos_gram(X, regularlizer=np.float32(0.000001)))
print(pos_gram(X, regularlizer=np.float32(0.00000006)))
print(pos_gram(X, regularlizer=np.float32(0.000000000001)))

[[1.0000001 0.       ]
 [0.        1.0000001]]
[[1.0000001 1.       ]
 [1.        1.0000001]]
[[1.000001 1.      ]
 [1.       1.000001]]
[[1.0000001 1.       ]
 [1.        1.0000001]]
[[1.0000001 1.       ]
 [1.        1.0000001]]


## Torch version

In [3]:
import torch

def pos_gram(gram, regularlizer = None):
    _size = len(gram)
    
    
    if regularlizer is None:
        # the fraction of float32 is 2**(-23)~10**(-7) we start with 10**(-7) times of maximun element
        regularlizer = gram.abs().max()*0.0000001
        if gram.abs().max() == 0:
            raise ValueError("gram error, expect matrix with none-zero element")
    
    if regularlizer <= 0:
        raise ValueError("regularlizer error, expect positive, got %s" %(regularlizer))
    
    while True:
        lambdas, vectors = torch.symeig(gram + torch.eye(_size)*regularlizer)
        if lambdas.min() > 0:
            break
        
        regularlizer *= 2.
    
    return gram + torch.eye(_size)*regularlizer

In [4]:
X =torch.eye(2)
print(pos_gram(X))

X = torch.ones((2,2))
print(pos_gram(X))
print(pos_gram(X, regularlizer=torch.tensor(0.000001)))
print(pos_gram(X, regularlizer=torch.tensor(0.00000006)))
print(pos_gram(X, regularlizer=torch.tensor(0.000000000001)))

tensor([[1.0000, 0.0000],
        [0.0000, 1.0000]])
tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]])
tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]])
tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]])
tensor([[1.0000, 1.0000],
        [1.0000, 1.0000]])
